
#ifndef HAL_LCD_HANDLER_V1_LCD_ERR_H_
#define HAL_LCD_HANDLER_V1_LCD_ERR_H_

#define RT_OK						1
#define RT_WRONG_COLUMN_NUMBER		2
#define	RT_WRONG_ROW_NUMBER			3

#endif /* HAL_LCD_HANDLER_V1_LCD_ERR_H_ */
