

#ifndef HAL_FLEX_SENSOR_HANDLER_V1_FLEX_SENSOR_ERR_H_
#define HAL_FLEX_SENSOR_HANDLER_V1_FLEX_SENSOR_ERR_H_

#define FLEX_GET_VALUE_RT_IS_OK							(u8)1
#define FLEX_GET_VALUE_RT_IS_SENSOR_NOT_ENABLED			(u8)2
#define FLEX_GET_VALUE_RT_IS_WRONG_SENSOR_NUMBER		(u8)3

#endif /* HAL_FLEX_SENSOR_HANDLER_V1_FLEX_SENSOR_ERR_H_ */
